config/routes.rb
Rails.application.routes.draw do
  get 'rooms/new'
  get '/users/sign_up'
  get '/users/sign_in'
  get '/users/profile'
  get '/users/acount'
  post '/users/login'
  post '/users/logout'
  patch '/users/renewal'
  get '/rooms/posts'
  get '/rooms/search'
  resources :users, only: [:create, :edit, :update]
  resources :rooms, only: [ :create, :show]
  resources :reservations, only: [:index, :new, :create, :show]
  get '/', to: 'home#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :room
  validates :start_at, {presence: true}
  validates :end_at, {presence: true}
  def start_end_check
    errors.add(:end_at, "は今日以降の日付で選択してください。") unless
    :start_at > :end_at 
  end
end

app/models/room.rb
class Room < ApplicationRecord
  mount_uploader :image_name, ImageNameUploader
  belongs_to :user
  has_many :reservations
  validates :name, {presence: true}
  validates :introduction, {presence: true}
  validates :price, {presence: true}
  validates :address_building, {presence: true}
  validates :image_name, {presence: true}
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image_name, ImageNameUploader
  has_many :rooms
  has_secure_password(validations: false)
  validates :name,  {presence: true}
  validates :email, {presence: true, uniqueness: true}
  validates :password, presence: true, length: { minimum: 6 }, on: :create, on: :update
  validates :image_name, presence: true, on: :renewal
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_login_user

  def set_login_user
    @user = User.find(session[:user_id]) if session[:user_id]
  end

  def search
    Room.where()
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
    @users = User.all
    @rooms = Room.all
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @user = User.find(session[:user_id])
    @reservations = Reservation.all
  end

  def new
    @user = User.find(session[:user_id])
    @room = Room.find(params[:room_id])
    @reservation = Reservation.new
    @reservation.start_at = Date.parse(params[:start_at])
    @reservation.end_at = Date.parse(params[:end_at])
    @room.person_num = params[:person_num]
    @days = (@reservation.end_at.to_date - @reservation.start_at.to_date).to_i
    @total = (@days * @room.price * @room.person_num).to_i
  end

  def create
    @user = User.find(session[:user_id])
    @room = Room.find(params[:reservation][:room_id])
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      redirect_to reservation_path(@reservation.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(session[:user_id])
    @room = Room.find(params[:id])
    @reservation = Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(
    :start_at,
    :end_at,
    :total_price,
    :room_id
    )
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def posts
    @rooms = Room.all
  end
  
  def new
    @room = Room.new
    @user = User.find(session[:user_id])
  end

  def create
    @user = User.find(session[:user_id])
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_path(@room.id)
    else
      render :new
    end
  end

  def show
    @room = Room.find(params[:id])
  end

  def search
    if params[:search_area].present?
      @rooms = Room.where('rooms.address_building LIKE (?)', "%#{params[:search_area]}%")
    elsif params[:search_keyword].present?
      @rooms = Room.where('rooms.address_building LIKE (?) OR rooms.name LIKE (?) OR rooms.introduction LIKE (?)', "%#{params[:search_keyword]}%", "%#{params[:search_keyword]}%", "%#{params[:search_keyword]}%")
    else
      @rooms = Room.all
    end
  end

  def posts
    @rooms = Room.all
  end

  private

  def room_params
    params.require(:room).permit(
    :name,
    :introduction,
    :price,
    :address_building,
    :image_name,
    :person_num
    ).merge(user_id: session[:user_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def sign_up
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "ユーザー登録が完了しました"
      redirect_to("/users/profile")
    else
      flash[:failure] = "ユーサー登録できませんでした"
      render("users/sign_up")
    end
  end

  def sign_in
    @user = User.new
  end

  def login
    @user = User.find_by(email: params[:user][:email])
    if @user && @user&.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      flash[:success] = "ログインしました"
      redirect_to("/")
    else
      @user = User.new
      flash[:failure] = "ログインできませんでした"
      @email = params[:email]
      render("users/sign_in")
    end
  end

  def acount
    @user = User.find(session[:user_id])
  end

  def edit
    @user = User.find(session[:user_id])
  end

  def update
    @user = User.find(session[:user_id])
    if @user.update(user_params)
      flash[:success] = "ユーザー情報を更新しました"
      redirect_to("/")
    else
      flash[:failure] = "ユーザー情報を更新できませんでした"
      render :edit
    end
  end

    

  def profile
    @user = User.find(session[:user_id])
  end

  def renewal
    @user = User.find(session[:user_id])
    @user.image_name = params[:user][:image_name] if params[:user][:image_name].present?
    @user.name = params[:user][:name]
    @user.introduction = params[:user][:introduction]
    if @user.image_name.present?
      if @user.save(validate: false)
        flash[:success] = "ユーザー情報を更新しました"
        redirect_to("/")
      else
        flash[:failure] = "ユーザー情報を更新できませんでした"
        render :profile
      end
    else
      flash[:failure] = "画像を入れてください"
      render :profile
    end
  end

  def logout
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to("/")
  end

  private

  def user_params
    params.require(:user).permit(
    :name,
    :email,
    :image_name,
    :password,
    :password_confirmation,
    :introduction
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?
    User.exists?(session[:user_id])
  end

  def current_user
    User.find(session[:user_id])
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class="notifications"></div>
<div class="top">
  <div class="top-main">
    <div class="container">
      <div class="row col-lg-6">
        <div class="form-fream">
          <div class="form-area">
            <p class="form-area-title mb-4">Potepan Shareでまだ体験したことのない旅をしよう</p>
            <%= form_tag(rooms_search_path, method: :get, local: true) do %>
              <label for="___">エリア</label>
              <input type="text" name="search_area" id="area" value="" class="form-control mb-4" placeholder="東京">
              <input type="submit" name="commit" value="探す" class="form-control btn-primary mb-4" data-disable-with="探す">
            <% end %>                    
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="panel-area m-5">
      <h1 class="section-title">おすすめのエリア</h1>
      <div class="row">
        <div class="panel-item col-lg-3 col-6">
          <span>東京</span>
          <a href="http://localhost:3000/rooms/search?search_area=%E6%9D%B1%E4%BA%AC&search_keyword=" >
            <img class="panel-image" src="/assets/img_tokyo.jpg">
          </a>
          <div class="shadow"></div>
        </div>
        <div class="panel-item col-lg-3 col-6">
          <span>大阪</span>
          <a href="http://localhost:3000/rooms/search?search_area=%E5%A4%A7%E9%98%AA&search_keyword=">
            <img class="panel-image" src="/assets/img_osaka.jpg">
          </a>
          <div class="shadow"></div>
        </div>
          <div class="panel-item col-lg-3 col-6">
          <span>京都</span>
          <a href="http://localhost:3000/rooms/search?search_area=%E4%BA%AC%E9%83%BD%E5%BA%9C&search_keyword=">
            <img class="panel-image shadow" src="/assets/img_kyoto.jpg">
          </a>
          <div class="shadow"></div>
        </div>
        <div class="panel-item col-lg-3 col-6">
          <span>札幌</span>
          <a href="http://localhost:3000/rooms/search?search_area=%E6%9C%AD%E5%B9%8C&search_keyword=">
            <img class="panel-image" src="/assets/img_sapporo.jpg">
          </a>
          <div class="shadow"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StayApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header-inner">
        <div class="header-left-nav">
          <a href="/">
            <img alt="サイトのロゴ画像" src="/assets/logo.png">
          </a>
          <%= form_tag(rooms_search_path, method: :get, local: true) do %>
            <div class="header-sharch d-lg-inline-block d-none">
              <input type="text" name="search_area" id="area" value="" class="form-control" placeholder="エリア">
              <i class="fas fa-map-marker-alt"></i>
            </div>
            <div class="header-sharch d-lg-inline-block d-none">
              <input type="text" name="search_keyword" id="keyword" value="" class="form-control" placeholder="キーワード">
              <i class="fas fa-search"></i>
            </div>
            <input type="submit" class="d-none" data-disable-with="">   
          <% end %>
        </div>
        <% if current_user? %>
          <div class="header-right-nav">
             <div class="nav-item d-sm-inline-block"><%= @user.name %></div> 
            <div class="nav-item">
              <% if @user.image_name? %> 
                <%= image_tag @user.image_name.url, class: "mx-3 p-1 host-icon nav-trigger"  %> 
              <% else %>
                <img class="mx-3 p-1 host-icon nav-trigger" alt="メニュー" src="s">
              <% end %> 
              <ul class="header-nav-menu">
                <li><%= link_to("ルーム登録", "/rooms/new") %></li>
                <li><%= link_to("予約済みルーム一覧", "/reservations") %></li>
                <li><%= link_to("登録済みルーム一覧", "/rooms/posts") %></li>
                <li><%= link_to("設定", "/users/acount") %></li>
                <li><%= link_to("ログアウト", "/users/logout", {method: :post}) %></li>
              </ul>
            </div>
          </div>
        <% else %>
          <div class="header-right-nav">
            <div class="nav-item">
              <p class="btn btn-primary my-2 mx-3">
                <%= link_to("ログイン", "/users/sign_in") %>
              </p>
              <p class="btn btn-secondary">
                <%= link_to("登録する", "/users/sign_up") %>
              </p>
            </div>
        </div>
        <% end %>
      </div>
    </header>
    <div class="clearfix">
    </div>
    <script>
      $(function() {
        $('.nav-trigger').click(function() {
          $('.header-nav-menu').toggle(1500);
        })
      });
    </script>
    <footer class="footer">
      <p>© 2020 POTEPAN.INC.</p>
      <% if flash[:success] %>
        <p class="success">
          <%= flash[:success] %>
        </p>
      <% elsif flash[:failure] %>
        <p class="failure">
          <%= flash[:failure] %>
        </p>
<% end %>
    </footer>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/reservations/index.html.erb
<div class="container-fiuld reservations">
  <h4 class="pb-4">予約済みルーム一覧</h4>
    <table>
      <thead>
        <tr align="center">
          <th>ルーム画像</th>
            <th>ルーム名</th>
            <th>ルーム紹介</th>
            <th>合計料金</th>
            <th>開始日</th>
            <th>終了日</th>
            <th>予約確定日時</th>
          </tr>
      </thead>
      <tbody>
        <% @reservations.each do |reservation| %>
        <tr>
          
          <td>
            <%= link_to room_path(reservation.room.id) do %>
              <%= image_tag reservation.room.image_name.url, class: "reservations-image"  %>
            <% end %>
          </td>
          <td class="posts-name"><%= reservation.room.name %></td>
          <td class="posts-content"><%= reservation.room.introduction %></td>
          <td class="price-icon"><%= reservation.total_price %></td>
          <td><%= reservation.start_at.to_date %></td>
          <td><%= reservation.end_at.to_date %></td>
          <td><%= reservation.created_at %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/reservations/new.html.erb
<div class="container reservations-new">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="reservations-new-nav">
        <h4 class="reservations-new-check-content">予約内容確認</h4>
        <h5 class="price-icon">¥<%= @room.price %>/日</h5>
        <div class="reservations-new-date-select">
          <%= form_tag(reservations_path, method: :post) do %>
            <input type="hidden" name="authenticity_token" value="ma6qoeMfV2UhEQWX4K9CnB7LULpfTuhJKuK2V1QdP1O5jJ1H1t3LTds61l4k2X8WhRCNFe7uru11MjzGpNY/yQ==">
            <input type="hidden" value="<%= @room.id %>" name="reservation[room_id]" id="reservation_room_id">
            <input type="hidden" value="<%= @user.id %>" name="reservation[user_id]" id="reservation_user_id">
            <label for="start_date">開始日</label>
            <input class="form-control mb-4" readonly="readonly" type="text"  value="<%= @reservation.start_at.to_date %>" name="reservation[start_at]" id="reservation_start_at">
            <label for="end_date">終了日</label>
            <input class="form-control mb-4" readonly="readonly" type="text" value="<%= @reservation.end_at.to_date %>" name="reservation[end_at]" id="reservation_end_at">
            <h6 class="reservations-new-check-content">使用日数 : <%= @days %>日</h6>
            <h6 class="reservations-new-check-content">人数 : <%= @room.person_num %>人</h6>
            <label for="total_amount">合計金額</label>
            <input class="form-control mb-4" readonly="readonly" type="text" value="<%= @total %>" name="reservation[total_price]" id="reservation_total_amount">
            <p class="reservations-new-check-content">上記内容でよろしければ「予約を確定」を押してください</p>
            <input type="submit" name="commit" value="予約を確定" class="btn btn-primary form-control my-3 btn4" data-disable-with="予約を確定">
            <p class="btn btn-secondary form-control "><%= link_to("ルーム詳細へ戻る", room_path(@room.id))%></p>
          <% end %>                
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reservations/show.html.erb
<div class="container-fiuld user"> 
  <div class="row">
    <div class="col-md-12 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <label class="col-md-3" for="room">予約した部屋</label>
            <div class="col-md-9">
              <p class="mt-10"><%= link_to(@room.name, room_path(@room.id)) %></p>
            </div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md-3" for="start_date">開始日</label>
            <div class="col-md-9"><%= @reservation.start_at.to_date %></div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md-3" for="end_date">終了日</label>
            <div class="col-md-9"><%= @reservation.end_at.to_date %></div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md-3" for="end_date">価格</label>
            <div class="col-md-9"><%= @reservation.total_price %>円</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="container-fiuld room-new">
  <div class="row">
    <div class="col-lg-2 room-nav room-nav-pc d-lg-block d-none">
      <ul>
        <li class="active">
          <a href="/rooms/new">基本情報</a>
        </li>
      </ul>
    </div>
    <div class="col-lg-2 room-nav room-nav-mobile d-lg-none">
      <ul>
        <li class="active">
          <a href="/rooms/new">基本情報</a>
        </li>
      </ul>
    </div>
    <div class="col-lg-10 room-view">
      <div class="room-view-box">
         <%= render 'layouts/shared/error', obj: @room %>
        <%= form_tag(rooms_path, {method: :post, multipart: true}) do %>
          <input type="hidden" name="authenticity_token">
          <div class="update-content">
            <div class="row">
              <h5>ルーム情報登録</h5>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <label class="col-md-3 required-a" for="name">ルーム名</label>
                <input class="form-control mb-4 col-md-9" placeholder="ルーム名を入力" type="text" name="room[name]" id="room_name">
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <label class="col-md-3 required-a" for="introduction">ルーム紹介</label>
              <textarea rows="5" class="form-control mb-4 col-md-9" placeholder="ルーム説明を入力" name="room[introduction]" id="room_content"><%= @room.introduction %></textarea>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <label class="col-md-3 required-a" for="price">料金</label>
              <input class="form-control mb-4 col-md-9" placeholder="一日あたりの料金を入力" type="number" name="room[price]" id="room_price">
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <label class="col-md-3 required-a" for="address_building">住所</label>
              <input class="form-control mb-4 col-md-9" placeholder="住所を入力" type="text" name="room[address_building]" id="room_address_building">
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <label class="col-md-3 required-a" for="image_name">ルーム画像</label>
              <input class="mb-4 col-md-9" placeholder="ルーム画像をアップロード" type="file" name="room[image_name]" id="room_image">
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <input type="submit" name="commit" value="登録" class="col-md-2 btn btn-primary mx-3" data-disable-with="登録">
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/posts.html.erb
<div class="container-fiuld room-posts">
  <h4 class="pb-4">登録済みルーム一覧</h4>
  <table>
    <thead>
      <tr align="center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>料金</th>
        <th>作成日</th>
      </tr>
    </thead>
    <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td>
              <%= link_to room_path(room.id) do %>
                <%= image_tag room.image_name.url, class:"room-posts-image" %>
              <% end %>
            </td>
            <td class="posts-name"><%= room.name %></td>
            <td class="posts-content"><%= room.introduction %></td>
            <td class="price-icon"><%= room.price %></td>
            <td><%= room.created_at %></td>
          </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/search.html.erb
<div class="container-fiuld room">
  <h4 class="pb-4">検索結果：<%= @rooms.count %>件</h4>
  <div class="row">
    <% @rooms.each do |room|%>
      <div class="col-sm-6 col-lg-4 col-xl-3">
        <div class="room-frame-inner">
          <%= link_to room_path(room.id) do %>
            <div class="room-image-out">
              <%= image_tag room.image_name.url, class: "room-image" %>
            </div>
            <div class="room-profile">
              <p class="room-profile-name"><%= room.name %></p>
              <p class="room-profile-city"><%= room.address_building %></p>
              <p class="room-profile-price price-icon"><%= room.price %></p>
            </div>
          <% end %>
        </div>
     </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container room-show">
  <div class="row">
    <%= render 'layouts/shared/error', obj: @room %>
    <div class="col-md-8">
      <%= image_tag @room.image_name.url, onerror: "this.onerror=null;this.src='/assets/room01.jpg';", alt: "部屋画像", class: "room-show-image" %>
      <div class="room-show-detile">
        <div class="room-show-detile-icon">
          <%= image_tag @user.image_name.url, class: "icon-image host-icon" %>
        </div>
        <div class="room-show-profile">
          <p class="room-show-profile-name"><%= @room.name %></p>
          <p class="room-show-profile-address"><%= @room.address_building %></p>
        </div>
      </div>
      <p class="room-show-detile-content"></p>
    </div>
    <div class="col-md-4">
      <div class="room-show-nav">
        <h5 class="price-icon">¥<%= @room.price %>/日</h5>
        <div class="room-show-date-select">
          <form action="/reservations/new" accept-charset="UTF-8" method="get">
            <label for="start_date">開始日</label>
            <input type="date" name="start_at" id="start_at" value="" class="form-control mb-4">
            <label for="end_date">終了日</label>
            <input type="date" name="end_at" id="end_at" value="" class="form-control mb-4">
            <label for="person_num">人数</label>
            <input type="number" name="person_num" id="person_num" value="" class="form-control mb-4">
            <input type="hidden" name="room_id" id="room_id" value="<%= @room.id %>">
            <input type="submit" name="commit" value="予約する" class="btn btn-primary form-control" data-disable-with="予約する">
          </form>        
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/acount.html.erb
<div class="container-fiuld user"> 
  <div class="row">
    <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
      <ul>
        <li class="active">
          <%= link_to("アカウント", "/users/acount") %>
        </li>
        <li class="">
          <%= link_to("プロフィール", "/users/profile") %>
        </li>
      </ul>
    </div>
    <div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
      <ul>
        <li class="active">
          <%= link_to("アカウント", "/users/acount") %>
        </li>
        <li class="">
          <%= link_to("プロフィール", "/users/profile") %>
        </li>
      </ul>
    </div>
    <div class="col-md-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <h5>アカウント</h5>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md-3" for="email">メールアドレス</label>
            <div class="col-md-9"><%= @user.email %></div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md-3" for="password">パスワード</label>
            <div class="col-md-9">*********</div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <p>
              <%= link_to "編集", edit_user_path(:user_id) %>
            </p><br>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container device">
  <div class="device_frame">
    <h2 class="mb-3">アカウント編集</h2>
    <%= render 'layouts/shared/error', obj: @user %>
    <% if flash[:failure] %>
      <p class="failure"><%= flash[:failure] %></p>
    <% end %>
    <div class="device_inner">
      <%= form_tag(user_path, {method: :patch}) do %>
        <input type="hidden" name="_method" value="put">
        <input type="hidden" name="authenticity_token" value="SvgHMiAaeO2QxR2q3//Rler+6kFjpwLHufq0ftx4Ggitw0VX7e6pkZOh61xde/SN/V1pOPe+DryHOrg6+MDWdw==">
        <div class="field">
          <div class="form-group">
            <label for="user_email">メールアドレス</label>
            <input autofocus="autofocus" autocomplete="email" class="form-control" placeholder="メールアドレスを入力してください" type="email"  name="user[email]" id="user_email">
          </div>
        </div>
        <div class="field">
          <div class="form-group">
            <label for="user_password">変更後パスワード（変更する場合のみ入力）</label>
            <input autocomplete="new-password" class="form-control" type="password" name="user[password]" id="user_password">
          </div>
        </div>
        <div class="field">
          <div class="form-group">
            <label for="user_password_confirmation">パスワード確認用（変更する場合のみ入力）</label>
            <input autocomplete="new-password" class="form-control" type="password" name="user[password_confirmation]" id="user_password_confirmation">
          </div>
        </div>
        <div class="field">
          <label for="user_current_password">現在のパスワード</label>
          <input autocomplete="current-password" class="form-control" placeholder="現在のパスワードを入力" type="password" name="user[current_password]" id="user_current_password">
        </div>
        <div class="actions">
          <input type="submit" name="commit" value="更新" class="form-control btn-primary my-4" data-disable-with="更新">
        </div>
        <div class="actions">
          <p>
            <%= link_to("戻る", "/users/acount") %>
          </p>
        </div>
      <% end %>  
    </div> 
  </div>
</div>

app/views/users/sign_up.html.erb
<div class="container device">
  <%= render 'layouts/shared/error', obj: @user %>
  <% if flash[:failure] %>
    <p class="failure"><%= flash[:failure] %></p>
  <% end %>
  <div class="device_frame">
    <p class="my-4">新しいアカウントを作成</p>
    <div class="device_inner">
      <%= form_tag(users_path, {method: :post}) do %> 
        <input type="hidden" name="authenticity_token" value="n9ucSbnvWuA+MGtY8wUM5Vwcmk0AHDWCh00jAtovgf94yUl0oL6XBhex+oVVQE+IeLUSpdMohxbi4xU++iZ6tg==">
        <div class="field form-row">
          <div class="col-2 required-b pt-2"></div>
          <input autocomplete="name" class="form-control col-10 px-2" placeholder="ユーザー名" type="text" name="user[name]" id="user_name" required>
        </div>
        <div class="field form-row">
          <div class="col-2 required-b pt-2"></div>
          <input autocomplete="email" class="form-control col-10 px-2 req" placeholder="メールアドレス" type="email" value="" name="user[email]" id="user_email" >
        </div>
        <div class="field form-row">
          <div class="col-2 required-b pt-2"></div>
          <input autocomplete="new-password" class="form-control col-10 px-2" placeholder="パスワード" type="password" name="user[password]" id="user_password" required>
        </div>
        <div class="field form-row">
          <div class="col-2 required-b pt-2"></div>
          <input autocomplete="new-password" class="form-control col-10 px-2" placeholder="パスワード確認" type="password" name="user[password_confirmation]" id="user_password_confirmation" required>
        </div>
        <div class="actions">
          <input type="submit" name="commit" value="新しいアカウントを作成" class="form-control btn-primary my-4 " data-disable-with="新しいアカウントを作成">
        </div>
      <% end %>        
      <p>
        <%= link_to("すでにアカウントをお持ちの方はログイン", "/users/sign_in") %>
      </p>
      <br>
    </div>
  </div>
</div>